# Uncomment the next line to define a global platform for your project
platform :ios, '15.5'

target 'Eventos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'Kingfisher', '~> 7.3.0'
  pod 'IQKeyboardManagerSwift', '6.3.0'
  pod "ToastViewSwift"

  target 'EventosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EventosUITests' do
    # Pods for testing
  end

end
